version: "3.8"

services:

  accounts:
    image: 241174/bank-account-dockerfile:latest
    mem_limit: 700m
    ports:
      - "9600:8080"
    networks:
      - localbank-network
    
  loans:
    image: 241174/bank-loans-dockerfile:latest
    mem_limit: 700m
    ports:
      - "9602:8082"
    networks:
      - localbank-network
    
  cards:
    image: 241174/bank-card-dockerfile:latest
    mem_limit: 700m
    ports:
      - "9601:8081"
    networks:
      - localbank-network
    
networks:
  localbank-network: